### PR TITLE
Add 1.17+ support [ tested on versions in description ] 

### PR DESCRIPTION
**Pull request by LuciferMorningstarDev**
Tested plugin support in these MC versions 1.9.4, 1.16.5, 1.17.1, 1.19.2.

Fixed "void" generator ( if id = "." ) adding bedrock to the ground
Some code reformatting

### CODE REVIEW

**Comment by nvx** [comment]
I'm trying to work out why the two separate generator classes? They both appear to extend from the same base class?

**Comment by LuciferMorningstarDev** [comment]
> I'm trying to work out why the two separate generator classes? They both appear to extend from the same base class?

Yeah sorry for the late reply... and yes... just the methods changed not the base class ChunkGenerator 
and depending on the version the plugin loads an instance of one or the other class

**Comment by LuciferMorningstarDev** [comment]
> > I'm trying to work out why the two separate generator classes? They both appear to extend from the same base class?
> 
> Yeah sorry for the late reply... and yes... just the methods changed not the base class ChunkGenerator and depending on the version the plugin loads an instance of one or the other class

in latest versions (all after 1.18) the old methods are removed and in 1.17 they're just deprecated thats why im using the bukkit version 1.17 as lib... there are both methods inside the ChunkGenerator class 
the new chunk generator gets loaded when version is higher or equal to 1.17

**Comment by nvx** [comment]
> > > I'm trying to work out why the two separate generator classes? They both appear to extend from the same base class?
> > 
> > 
> > Yeah sorry for the late reply... and yes... just the methods changed not the base class ChunkGenerator and depending on the version the plugin loads an instance of one or the other class
> 
> in latest versions (all after 1.18) the old methods are removed and in 1.17 they're just deprecated thats why im using the bukkit version 1.17 as lib... there are both methods inside the ChunkGenerator class the new chunk generator gets loaded when version is higher or equal to 1.17

yeah I'm still not following why it needs two separate classes though, rather than just having one class that implements both the new and old methods?

**Comment by LuciferMorningstarDev** [comment]
just to have that separately its clearer

**Comment by nvx** [comment]
It also means the code is massively duplicated, and the change is a lot larger than it needs to be which really would be just implementing a couple of new methods (one of which is empty, the other of which could share code with the existing method) and bumping a dependency version.

**Comment by StealthyExpertX** [comment]
Hows support for 1.19.2 look? How far out before an update rolls out?

**Pull request closed without merging**
